#ifndef __grammar
#define __grammar
#define VAR_KEYWORD       "var"
#define CONST_KEYWORD     "const"
#define PROC_KEYWORD      "func"
#define STRUCT_KEYWORD    "estrutura"
#define ENUM_KEYWORD      "enumeracao"
#define UNION_KEYWORD     "uniao"
			  
#define RETURN_KEYWORD    "retorne"
#define BREAK_KEYWORD     "parar"
#define CONTINUE_KEYWORD  "continue"
#define IF_KEYWORD        "se"
#define ELIF_KEYWORD      "ouse"
#define ELSE_KEYWORD      "senao"
#define WHILE_KEYWORD     "enquanto"
#define DO_KEYWORD        "faca"
#define SWITCH_KEYWORD    "switch"
#define LOCAL_KEYWORD     "local"
#define TYPEDEF_KEYWORD   "tipodata"
#define NAMESPACE_KEYWORD "namespace"
#define UNSIGNED_KEYWORD  "unsigned"
#define AS_KEYWORD        "como"
#define OR_KEYWORD        "ou"
#define AND_KEYWORD       "e"
#define INCLUDE_KEYWORD   "incluir"
#endif /* __grammar */
